### ISSUE TITLE
How do I use the .add_doc functionality to figure out the distribution for an unseen document

### ISSUE THREAD

**Issue by MattCrawford68** [ankane/tomoto-ruby#3]
Hi,

In the tomoto api, there's an method to calculate the scores for the individual topics for a new, unseen document.  It was obvious to me how to do this in the ruby implementation

**Comment by ankane** [comment]
Hey @MattCrawford68, added support in the commit above. You can try it out with:

```ruby
gem 'tomoto', github: 'ankane/tomoto', submodules: true
```

And:

```ruby
doc = model.make_doc("unseen doc")
topic_dist, ll = model.infer(doc)
```
