### ISSUE TITLE
M1 Mac Issue: the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by eichert12** [ankane/tomoto-ruby#4]
Currently when trying to install the gem on an M1 the following error occurs:

the clang compiler does not support '-march=native'

**Comment by ankane** [comment]
Hey @eichert12, thanks for reporting! Just pushed a fix.

**Comment by ankane** [comment]
Also, to pull the gem from GitHub, use `submodules: true`:

```ruby
gem "tomoto", github: "ankane/tomoto-ruby", submodules: true
```

**Comment by eichert12** [comment]
Excellent, thanks.  As an FYI, while researching the bug I came across a few posts that suggested clang 15 on Mac will support the native flag.

**Comment by eichert12** [comment]
Are there other pre-requisites or setup steps required?  I'm getting compiler errors when trying to use the latest gem (via adding the above recommended line to the gem file).  Getting errors if I pull source and compile as well.

Notable errors:
tomoto-ruby/vendor/eigen/Eigen/src/Core/CoreEvaluators.h:790:23: error: no matching member function for call to 'packetOp'
tomoto-ruby/vendor/tomotopy/src/TopicModel/../Utils/EigenAddonOps.hpp:140:12: error: use of undeclared identifier 'lgamma_subt'

-----

4 errors generated.
make: *** [HLDAModel.o] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
.rbenv/versions/3.0.3/bin/bundle:23:in `load'
.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => compile => compile:arm64-darwin21 => compile:tomoto:arm64-darwin21 => copy:tomoto:arm64-darwin21:3.0.3 => tmp/arm64-darwin21/tomoto/3.0.3/tomoto.bundle

**Comment by ankane** [comment]
My bad, Tomoto doesn't support ARM yet: https://github.com/bab2min/tomotopy/issues/170#issuecomment-1164581847

**Comment by ankane** [comment]
Added a note to the readme

**Comment by bab2min** [comment]
@ankane 
From v0.12.4, `tomotopy` supports ARM Neon architecture. You can check the recent update!

**Comment by ankane** [comment]
Awesome, big thanks @bab2min! Working on updating it now.

**Comment by ankane** [comment]
Just pushed 0.3.2
